// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCMjSvtAsvUj8qLBvxolrkwM_c6hUAS7JE',
    appId: '1:651467935322:web:3188ac31cbaf1827fed263',
    messagingSenderId: '651467935322',
    projectId: 'coffee-edad9',
    authDomain: 'coffee-edad9.firebaseapp.com',
    storageBucket: 'coffee-edad9.appspot.com',
    measurementId: 'G-1MBBPM5WLH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDzFq7tUsWR0V-CPRmoHFa1g_5gH2T4Gmo',
    appId: '1:651467935322:android:331a1229993a06fffed263',
    messagingSenderId: '651467935322',
    projectId: 'coffee-edad9',
    storageBucket: 'coffee-edad9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAfup9x4wDg3vz_ZlsmRMWmU5Wt8DswzpI',
    appId: '1:651467935322:ios:c930888f3e1adb29fed263',
    messagingSenderId: '651467935322',
    projectId: 'coffee-edad9',
    storageBucket: 'coffee-edad9.appspot.com',
    iosBundleId: 'com.example.coffee',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCMjSvtAsvUj8qLBvxolrkwM_c6hUAS7JE',
    appId: '1:651467935322:web:be95694375be943cfed263',
    messagingSenderId: '651467935322',
    projectId: 'coffee-edad9',
    authDomain: 'coffee-edad9.firebaseapp.com',
    storageBucket: 'coffee-edad9.appspot.com',
    measurementId: 'G-J8Y6T9JMWJ',
  );

}